name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Deploy to Vercel
        if: success()
        run: |
          git config --global user.email "nathalylozano@uninorte.edu.co"
          git config --global user.name "Nath1234567"
          git remote set-url origin https://Nath1234567:${{ secrets.GH_PAT }}@github.com/Nath1234567/proyecto-vivienda.git
          git push origin main
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.11-9/x64
          JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.11-9/x64
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
          GH_PAT: ${{ secrets.GH_PAT }}
          TOKEN_GIT: ${{ secrets.TOKEN_GIT }}
