name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Set environment variables
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV

      - name: Deploy to Vercel
        if: success()
        run: |
          npm install -g vercel   # Instala Vercel CLI (si no está instalado)
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod   # Despliega a producción en Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Push changes to GitHub
        if: success()
        run: |
          git config --global user.email "nathalylozano@uninorte.edu.co"
          git config --global user.name "Nath1234567"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}